# A production cluster: three servers and three agents that offer storage.
all:
  children:
    k3s_servers:
      hosts:
        nighthawk-server-1:
          ansible_host: 192.0.2.31
        nighthawk-server-2:
          ansible_host: 192.0.2.32
        nighthawk-server-3:
          ansible_host: 192.0.2.33
    k3s_agents:
      hosts:
        nighthawk-agent-1:
          ansible_host: 192.0.2.41
        nighthawk-agent-2:
          ansible_host: 192.0.2.42
        nighthawk-agent-3:
          ansible_host: 192.0.2.43
